# Generated by Django 4.0.5 on 2022-07-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('superuser', 'superuser')], max_length=10),
        ),
    ]
