# Generated by Django 4.0.5 on 2022-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Must be in E.164 format i.e. +xxxxxxxxxxx', max_length=14, unique=True),
        ),
    ]
