# Generated by Django 4.0.5 on 2022-07-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(help_text='Supported content types: [jpg, jpeg, png]', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(help_text='Must be in format YYYY-MM-DD. Must be in the past'),
        ),
    ]
